[package]
name = "json-parse"
version = "1.0.0"
edition = "2021"

authors = ["agubelu"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/agubelu/json-parse"
description = "A low-level JSON parser for Rust with a simple API and full spec support."

[dependencies]
