on: [push]

name: run_tests

jobs:
  test:
    name: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - run: |
          cargo test
          cargo test --release